server.port=8080

# Database (Postgres container)
spring.datasource.url=jdbc:postgresql://postgres:5432/order_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Zipkin (docker)
spring.zipkin.base-url=http://zipkin:9411

# Eureka (docker)
eureka.client.service-url.defaultZone=http://eureka:password@discovery-server:8761/eureka

# Kafka (docker)
spring.kafka.bootstrap-servers=broker:29092


