spring.application.name=product-service
server.port=8080

# MongoDB (Docker service name = mongo)
spring.data.mongodb.uri=mongodb://mongo:27017/product-service

# Eureka (Docker service name = discovery-server)
eureka.client.service-url.defaultZone=http://eureka:password@discovery-server:8761/eureka
eureka.instance.hostname=product-service
eureka.instance.prefer-ip-address=true

# Zipkin (Docker service name = zipkin)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
