spring.data.mongodb.uri=mongodb://localhost:27017/product-service
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address= true
eureka.instance.hostname=localhost


#eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
# dns eureka problem
eureka.instance.instance-id=${spring.application.name}:${server.port}
# Ensure correct port gets registered (especially when using random)
#eureka.instance.non-secure-port-enabled=true
#eureka.instance.non-secure-port=${server.port}


spring.application.name=product-service
server.port=0
spring.output.ansi.enabled=ALWAYS

# Zipkin tracing
management.tracing.sampling.probability=1.0
spring.zipkin.base-url=http://localhost:9411/api/v2/spans
spring.zipkin.sender.type=web
management.endpoints.web.exposure.include=*
